apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: welcome
          image: dragz17/sltr-devops-boy:staging
          env:
            - name: ENV
              value: "staging"
