apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-testing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dragz17/simple-app-manifest.git'
    targetRevision: HEAD
    path: manifest/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

